#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_6,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_7,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_8,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           b1m1,          tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           b1m2,          tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port4,           b2m1,          tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port5,           b2m2,          tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port6,           b3m1,          tmotorVex393_MC29, openLoop, encoderPort, I2C_5)
#pragma config(Motor,  port7,           b3m2,          tmotorVex393_MC29, openLoop, encoderPort, I2C_6)
#pragma config(Motor,  port8,           b4m1,          tmotorVex393_MC29, openLoop, encoderPort, I2C_7)
#pragma config(Motor,  port9,           b4m2,          tmotorVex393_MC29, openLoop, encoderPort, I2C_8)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

#include "PidCore.h"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

struct pid bay1mot1, bay1mot2, bay2mot1, bay2mot2, bay3mot1, bay3mot2, bay4mot1, bay4mot2;

task usercontrol()
{
	pid_arr[pid_count++] = &bay1mot1;
	pid_arr[pid_count++] = &bay1mot2;
	pid_arr[pid_count++] = &bay2mot1;
	pid_arr[pid_count++] = &bay2mot2;
	pid_arr[pid_count++] = &bay3mot1;
	pid_arr[pid_count++] = &bay3mot2;
	pid_arr[pid_count++] = &bay4mot1;
	pid_arr[pid_count++] = &bay4mot2;

	bay1mot1.mport = b1m1;
	bay1mot2.mport = b1m2;
	bay2mot1.mport = b2m1;
	bay2mot2.mport = b2m2;
	bay3mot1.mport = b3m1;
	bay3mot2.mport = b3m2;
	bay4mot1.mport = b4m1;
	bay4mot2.mport = b4m2;

	pid_init_all();

	//bay1mot2.revenc = true;
  // User control code here, inside the loop
	startTask(pid_run_loops, 100);

  while (true)
  {
  	bay1mot1.mtarget += vexRT[Ch1]/3;
  	bay1mot2.mtarget += vexRT[Ch1]/3;
  	bay2mot1.mtarget += vexRT[Ch1]/3;
  	bay2mot2.mtarget += vexRT[Ch1]/3;
  	bay3mot1.mtarget += vexRT[Ch1]/3;
  	bay3mot2.mtarget += vexRT[Ch1]/3;
  	bay4mot1.mtarget += vexRT[Ch1]/3;
  	bay4mot2.mtarget += vexRT[Ch1]/3;
    wait1Msec(5);
  }
}
