#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    stower,         sensorPotentiometer)
#pragma config(Sensor, dgtl1,  inRed,          sensorDigitalIn)
#pragma config(Sensor, dgtl2,  inTop,          sensorDigitalIn)
#pragma config(Sensor, dgtl11, redInd,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, topInd,         sensorLEDtoVCC)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_6,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_7,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           lbdrive,       tmotorVex393_HBridge, openLoop, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port2,           lfdrive,       tmotorVex393_MC29, openLoop, reversed, driveLeft, encoderPort, I2C_2)
#pragma config(Motor,  port3,           grabber,       tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port4,           catipult,      tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port6,           elbow,         tmotorVex393_MC29, openLoop, encoderPort, I2C_7)
#pragma config(Motor,  port7,           tower,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rbdrive,       tmotorVex393_MC29, openLoop, reversed, driveRight, encoderPort, I2C_6)
#pragma config(Motor,  port9,           grabberslave,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rfdrive,       tmotorVex393_HBridge, openLoop, driveRight, encoderPort, I2C_5)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include "PidCore.h"
#include "GameState.h"
#include "Movement.h"

#define LOADER_UP 15
#define LOADER_DOWN -165

//627.2 Ticks/Rotation at motor = 1881.6 Ticks/Rotation at loader.
//These two numbers should add to 1881.6 (decimals don't work so 1882).
#define CATIPULT_ARM 1800
#define CATIPULT_FIRE 82

#define CATIPULT_ARMED true
#define CATIPULT_FIRED false

#define TOWER_RATIO -0.7

#define TOWER_UP 2858
#define ELBOW_UP -720
#define TOWER_DOWN 184
#define ELBOW_DOWN -210

bool catipultState = CATIPULT_FIRED;
bool buttonReleased = true;

bool loaderUp = true;
bool loaderButtonReleased = true;
bool SlowMode = false;
bool switchDir = false;
bool dirBtnReleased = true;

struct pid pcatipult, pgrabber;
struct pid plfdrive, plbdrive, prfdrive, prbdrive;
struct pid pelbow; //ptower

int towermtarget = 184;
int towerisum;
long towermin = 184, towermax = 3240;

void enableDrivePid();
void autonBottom();
void autonTop();

//Adjusts the LEDs based on what's happening.
//If the Red LED is on then you are on the RED team.
//If the Green LED is on then you are at the FLAG end (top);
task setLed(){
	while(true){
		if(SensorValue[inRed] == 1){
			SensorValue[redInd] = 1;
		}else{
			SensorValue[redInd] = 0;
		}
		if(SensorValue[inTop] == 1){
			SensorValue[topInd] = 1;
		}else{
			SensorValue[topInd] = 0;
		}
		wait1Msec(100);
	}
}

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
	// If this is enabled our pid task shuts down. We need this to false.
  bStopTasksBetweenModes = false;

  pcatipult.mport = catipult;
  pgrabber.mport = grabber;

  plfdrive.mport = lfdrive;
  plbdrive.mport = lbdrive;
  prfdrive.mport = rfdrive;
  prbdrive.mport = rbdrive;

  //ptower.mport = tower;
  pelbow.mport = elbow;

  pid_arr[pid_count++] = &pcatipult;
  pid_arr[pid_count++] = &pgrabber;

  pid_arr[pid_count++] = &plfdrive;
  pid_arr[pid_count++] = &plbdrive;
  pid_arr[pid_count++] = &prfdrive;
  pid_arr[pid_count++] = &prbdrive;

  //pid_arr[pid_count++] = &ptower;
  pid_arr[pid_count++] = &pelbow;

  pid_init_all();

  pcatipult.pgain = 2.0;
  pcatipult.dgain = 0.5;
  pcatipult.lowpass = 64;

  pgrabber.max = 25;
  pgrabber.min = -174;
  pgrabber.pgain = 2.0;
  pgrabber.igain = 0.05;
  pgrabber.ilimit = 1500;
  pgrabber.lowpass = 30;
  pgrabber.mtarget = LOADER_UP;

  /*ptower.igain = 0.1;
  ptower.min = 0;
  ptower.max = 1535;*/

  pelbow.igain = 0.001;
  pelbow.pgain = 0.7;
  pelbow.min = -865;
  pelbow.max = 0;
  pelbow.enable = false;

  //Setup the api for moving things
  setupMovements(&plfdrive, &plbdrive, &prfdrive, &prbdrive, 392, 10.16, 36.35375);

  slaveMotor(grabberslave, grabber);

  //Should almost always be the last thing that happens.
  startTask(pid_run_loops, 50);
  startTask(setLed, 50);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	if(plfdrive.enable == false){
		enableDrivePid();
	}
	bool end = false;
	bool alliance = false;
	if(SensorValue[inTop] == 1){
		end = TOP;
	}else{
		end = BOTTOM;
	}
	if(SensorValue[inRed] == 1){
		alliance = RED;
	}else{
		alliance = BLUE;
	}
	initGameState(alliance, end);

	//Tower prep
	pelbow.mtarget = ELBOW_DOWN;
	towermtarget = TOWER_DOWN;
	//wait_ontarget(&pelbow);

	//End tower prep
	driveBackwards(1100, true);
	towermtarget = 500;
	waitUntil(SensorValue[stower]-500 < 16);
	if(isStartBottom()){
		turnUp(300, true);
	}else{
		turnDown(300, true);
	}
	driveForwards(200, true);
	pelbow.mtarget = 0;
	//wait_ontarget(&pelbow);
}

void enableDrivePid(){
	plfdrive.enable = true;
	plbdrive.enable = true;
	prfdrive.enable = true;
	prbdrive.enable = true;
}

void autonBottom(){
	writeDebugStreamLine("Bottom");
	//Tower prep
	pelbow.mtarget = ELBOW_DOWN;
	towermtarget = TOWER_DOWN;
	wait_ontarget(&pelbow);

	//End tower prep
	driveBackwards(1100, true);
	turnUp(300, true);
	driveForwards(200, true);
	pelbow.mtarget = 0;
	wait_ontarget(&pelbow);
}

void autonTop(){
	writeDebugStreamLine("Top");
	//Tower prep
	pelbow.mtarget = ELBOW_DOWN;
	towermtarget = TOWER_DOWN;
	wait_ontarget(&pelbow);

	//End tower prep
	driveBackwards(1100, true);
	turnDown(300, true);
	driveForwards(200, true);
	pelbow.mtarget = 0;
	//wait_ontarget(&pelbow);
}

//int timer = -1;
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
task usercontrol()
{
  // User control code here, inside the loop

	//Setup Stuff
	//Disable drive Pid Control
	plfdrive.enable = false;
	plbdrive.enable = false;
	prfdrive.enable = false;
	prbdrive.enable = false;

	pcatipult.mtarget = CATIPULT_ARM;

  while (true)
  {
  	if(vexRT[Btn5D] == 1 && vexRT[Btn5U] == 1 && vexRT[Btn6D] == 1 && vexRT[Btn5U] == 1)
  	{
  		SlowMode = true;
  	}else {
  		SlowMode = false;
  	}

  	if(vexRT[Btn8R] == 1){
  		if(dirBtnReleased){
  			switchDir = !switchDir;
  			dirBtnReleased = false;
  		}
  	}else if(vexRT[Btn8R] == 0){
  		dirBtnReleased = true;
  	}

  	//Perim Drive
  	short lpower = vexRT[Ch3];
  	//lpower*=-1;
  	lpower = lowpassS(lpower, 16);
  	short rpower = vexRT[Ch2];
  	//rpower*=-1;
  	rpower = lowpassS(rpower, 16);

  	if(switchDir){
  		lpower *= -1;
  		rpower *= -1;
  		short buffer = lpower;
  		lpower = rpower;
  		rpower = buffer;
  	}

  	if(!SlowMode){
    	motor[lfdrive] = lpower;
  		motor[lbdrive] = lpower;
  		motor[rfdrive] = rpower;
  		motor[rbdrive] = rpower;
  	}else{
  		motor[lfdrive] = lpower/2;
  		motor[lbdrive] = lpower/2;
  		motor[rfdrive] = rpower/2;
  		motor[rbdrive] = rpower/2;
  	}

  	if(vexRT[Btn8L] == 1 && buttonReleased){
  		/*if(catipultState == CATIPULT_FIRED){
  			pcatipult.mtarget+=CATIPULT_ARM;
  			catipultState = CATIPULT_ARMED;
  		}else if(catipultState == CATIPULT_ARMED){
  			pcatipult.mtarget+=CATIPULT_FIRE;
  			catipultState = CATIPULT_FIRED;
  		}*/
  		pcatipult.mtarget += CATIPULT_ARM+CATIPULT_FIRE;
  		buttonReleased = false;
  	}else if(vexRT[Btn8L] == 0){
  		buttonReleased = true;
  	}

  	if(vexRT[Btn7L] == 1 && loaderButtonReleased){
  		if(loaderUp){
  			pgrabber.mtarget = LOADER_DOWN;
 				loaderUp = false;
  		}else{
  			pgrabber.mtarget = LOADER_UP;
  			loaderUp = true;
  		}
  		loaderButtonReleased = false;
  	}else if(vexRT[Btn7L] == 0){
  		loaderButtonReleased = true;
  	}
  	if(vexRT[Btn5U] == 1 && SlowMode == false){
  		pgrabber.mtarget += 5;
  	}else if(vexRT[Btn5D] == 1 && SlowMode == false){
  		pgrabber.mtarget -= 5;
  	}
  	if(pgrabber.mtarget == LOADER_DOWN){
  		loaderUp = false;
  	}else if(pgrabber.mtarget == LOADER_UP){
  		loaderUp = true;
  	}

  	if(vexRT[Btn6U] == 1 && SlowMode == false){
  		towermtarget += 25;
  		pelbow.mtarget += TOWER_RATIO*10;
  	}else if(vexRT[Btn6D] == 1 && SlowMode == false){
  		towermtarget -= 25;
  		pelbow.mtarget -= TOWER_RATIO*10;
  	}

  	if(vexRT[Btn8U] == 1){
  		pelbow.mtarget+=10;
  	}else if(vexRT[Btn8D] == 1){
  		pelbow.mtarget-=10;
  	}

  	if(vexRT[Btn7U] == 1){
  		pelbow.mtarget = ELBOW_UP;
  		//timer = 50;
  		towermtarget = TOWER_UP;
  	}else if(vexRT[Btn7D] == 1){
  		//timer = -1;
  		pelbow.mtarget = ELBOW_DOWN;
  		towermtarget = TOWER_DOWN;
  	}
  	/*
  	if(timer == 0){
  		timer = -1;
  		pelbow.mtarget = ELBOW_UP;
  	}

  	if(timer > 0){
  		timer--;
  	}*/
    wait1Msec(20);
  }
}

void updateTower(){
	//Limit the pid loop
	if (towermin != 0 || towermax != 0) {
		towermtarget = LIMIT(towermtarget, towermin, towermax);
	}

	//Calculate initial values
	int enc = SensorValue[stower];

	//Calculate err using the modified enc value and the target.
	long err = towermtarget - enc;

	//P Component
	float corr = err * 0.15;

	//I Component
	towerisum+=err;
	if(towerisum >= 1000){
		towerisum = 1000;
	}else if(towerisum < 0){
		if(1000 < 0 && towerisum < 1000){
			towerisum = 1000;
		}else if(1000 > 0 && towerisum < 0){
			towerisum = -1000;
		}
	}

	corr += towerisum * 0.0;

	//writeDebugStreamLine("Powering motor at %d", corr);
	corr = lowpassI(corr, 32);
	motor[tower] = corr;
	//writeDebugStreamLine("Motor had power at %d", corr);
}
